env:
  commonjs: true
  node: true
  es2021: true
extends:
  - standard
globals:
  #  mocha global variables
  describe: false
  it: false
  before: false
  after: false
  beforeEach: false
  afterEach: false
parserOptions:
  ecmaVersion: 12
  sourceType: module