env:
  commonjs: true
  node: true
  es2021: true
extends:
  - standard
globals:
  #  mocha global variables
  describe: false
  it: false
  before: false
  after: false
  beforeEach: false
  afterEach: false
  afterAll: false
  test: false
  expect: false
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-case-declarations: 0
  eqeqeq: 0