version: '3'
services:
  knoow-data-storage-api-excercise:
    container_name: knoow-data-storage-api-excercise
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        DATA_STORAGE_SYSTEM:
        NODE_ENV:
        PORT:
        REDIS_HOST:
        REDIS_PORT:
    ports:
      - 3001:3001
    environment:
      DATA_STORAGE_SYSTEM:
      NODE_ENV: test
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
