version: '3'
services:
  knoow-data-storage-api-excercise:
    build:
      context: ./
      dockerfile: docker/knoow-data-storage-api-excercise/Dockerfile
    ports:
      - 3001:3001
    environment:
      DATA_STORAGE_SYSTEM: 'redis'
      NODE_ENV: local
      PORT: 3001
      REDIS_URL: redis://redis
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
  test-runner:
    build:
      context: ./
      dockerfile: docker/test-runner/Dockerfile
    command: npm run test
    environment:
      DATA_STORAGE_SYSTEM: 'redis'
      NODE_ENV: local
      PORT: 3001
      REDIS_URL: redis://redis
    links:
      - redis
    depends_on:
      - redis
